apiVersion: v2
name: remark42
description: A Helm chart for Remark42 comment system

type: application

maintainers:
  - name: p-bogdan

version: "0.6.1"

appVersion: "v1.12.1"

dependencies:
  - name: redis
    version: "0.7.2"
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: redis.enabled
