apiVersion: v2
name: commento
description: A Helm chart for Commento on Kubernetes

type: application

maintainers:
  - name: p-bogdan

version: "0.1.35"

appVersion: "v1.8.0"

dependencies:
  - name: postgres
    version: "0.5.0"
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: postgres.enabled
