version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      #interval: "weekly"
      #day: saturday
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
