apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes metrics-server

type: application

maintainers:
  - name: p-bogdan

version: 2.13.4

appVersion: "v0.5.1"

keywords:
  - metrics-server
