apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes

maintainers:
  - name: pbogdan

type: application

# This is the chart version.
version: 0.3.1

# This is the version number of the application being deployed.
appVersion: "5.7.0-apache"

dependencies:
  - name: mariadb
    version: 0.2.10
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: mariadb.enabled
