apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes

maintainers:
  - name: p-bogdan

type: application

# This is the chart version.
version: "0.9.2"

# This is the version number of the application being deployed.
appVersion: "6.3.2-apache"

dependencies:
  - name: mariadb
    version: "0.10.0"
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: mariadb.enabled
