apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: p-bogdan

version: "0.6.11"

appVersion: "5.1.7"

dependencies:
  - name: mongodb
    version: "0.6.0"
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: mongodb.enabled
  - name: elasticsearch
    version: "0.8.2"
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: elasticsearch.enabled
