apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: pbogdan

version: 0.1.14

appVersion: "4.0.6"

dependencies:
  - name: mongodb
    version: 0.2.10
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: mongodb.enabled
  - name: elasticsearch
    version: 0.1.1
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: elasticsearch.enabled
