apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: groundhog2k

version: "0.6.10"

appVersion: "5.1.7"

dependencies:
  - name: mongodb
    version: "0.5.19"
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: mongodb.enabled
  - name: elasticsearch
    version: "0.1.106"
    repository: "https://p-bogdan.github.io/lf-helm-charts"
    condition: elasticsearch.enabled
