name: Release helm chart

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Packaging artifacts
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION:1}" >> GITHUB_ENV
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package charts/ --destination=.cr-release-packages
      - name: Creating/Updating repo index
        run: |
          helm repo index --url https://p-bogdan.github.io/lf-helm-charts .
          ls -al
          helm repo add lf-charts https://p-bogdan.github.io/lf-helm-charts
          helm repo update
      #- name: Add dependencies
      #  run: |
      #    helm repo add lf-charts https://p-bogdan.github.io/lf-helm-charts
      - name: Run Release
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          #skip_packaging: true
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
